version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - nferreira1
    assignees:
      - nferreira1
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    labels:
      - dependencies
      - automated
        
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    reviewers:
      - nferreira1
    assignees:
      - nferreira1
    commit-message:
      prefix: ci
      include: scope
    labels:
      - github-actions
      - automated
